import { readFile, stat, writeFile } from "node:fs/promises";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { join } from "node:path";
import { root } from "./lib/repo.mjs";

const execFileAsync = promisify(execFile);

const targets = {
  "darwin-arm64": {
    packageDirectory: "packages/pdfium-node-darwin-arm64",
    prebuildDirectory: "prebuilds/darwin-arm64",
    libraryName: "libpdfium.dylib",
  },
  "linux-x64": {
    packageDirectory: "packages/pdfium-node-linux-x64-gnu",
    prebuildDirectory: "prebuilds/linux-x64-gnu",
    libraryName: "libpdfium.so",
  },
};

const currentTarget = `${process.platform}-${process.arch}`;
const target = targets[currentTarget];

if (!target) {
  console.log(`No native measurements configured for ${currentTarget}; skipping.`);
  process.exit(0);
}

const prebuildRoot = join(root, target.packageDirectory, target.prebuildDirectory);
const addonPath = join(prebuildRoot, "pdfium_node_native.node");
const libraryPath = join(prebuildRoot, target.libraryName);
const versionPath = join(prebuildRoot, "PDFIUM_VERSION");
const version = parseVersion(await readFile(versionPath, "utf8"));

const coldStart = await measureColdStart();
const addon = await stat(addonPath);
const library = await stat(libraryPath);

const markdown = `# Native Measurements

Generated by \`npm run measure:native\`.

## ${currentTarget}

- PDFium revision: \`${version}\`
- Native addon size: ${formatBytes(addon.size)}
- PDFium library size: ${formatBytes(library.size)}
- Cold-start PNG render: ${coldStart.durationMs.toFixed(2)} ms
- Output dimensions: ${coldStart.width}x${coldStart.height}
- Output bytes: ${coldStart.bytes}
`;

await writeFile(join(root, "docs/native-measurements.md"), markdown);
console.log(markdown);

async function measureColdStart() {
  const probe = `
    import { performance } from "node:perf_hooks";
    import { readFile } from "node:fs/promises";
    import { renderPdfThumbnails } from "@sebastian-software/pdfium-node";
    const pdf = await readFile("fixtures/simple-one-page.pdf");
    const start = performance.now();
    const [thumbnail] = await renderPdfThumbnails(pdf, {
      pages: [1],
      format: "png",
      maxWidth: 200,
      timeoutMs: 5000
    });
    const end = performance.now();
    console.log(JSON.stringify({
      durationMs: end - start,
      width: thumbnail.width,
      height: thumbnail.height,
      bytes: thumbnail.data.byteLength
    }));
  `;

  const { stdout } = await execFileAsync(
    process.execPath,
    ["--input-type=module", "--eval", probe],
    { cwd: root }
  );

  return JSON.parse(stdout);
}

function formatBytes(bytes) {
  return `${bytes} bytes (${(bytes / 1024 / 1024).toFixed(2)} MiB)`;
}

function parseVersion(text) {
  const values = Object.fromEntries(
    text
      .trim()
      .split("\n")
      .map((line) => line.split("=", 2))
  );

  if (values.MAJOR && values.MINOR && values.BUILD && values.PATCH) {
    return `${values.MAJOR}.${values.MINOR}.${values.BUILD}.${values.PATCH}`;
  }

  return text.trim();
}
